FROM golang:latest

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ../migrations migrations

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

CMD /go/bin/goose -dir=migrations postgres "host=postgres port=5432 user=dev password=dev dbname=dev sslmode=disable" up