HttpServer:
  Port: 9234
  AdminPort: 9235

Database:
  Main:
    Host: '127.0.0.1'
    SslMode: 'disable'
    Port: 5432
    User: 'postgres'
    Password: 'postgres'
    DbName: 'blog'
  Replica:
      Host: '127.0.0.1'
      SslMode: 'disable'
      Port: 5432
      User: 'postgres'
      Password: 'postgres'
      DbName: 'blog'